# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4a31cd244060bba67e8639a3e7c9d39ea8f112dc4f25afbc15dd60a17896df02a3566bad904a745291e7cb58cd4b98ed61975026bdd932fea8472566e5c321e

test:
  secret_key_base: c8c4abd1704f8a984a41fd33450013eab3e2a0523ffc64898ed5380c98872339dbfba54b81c86a43481a6cd890caff0be8d0e8215b86b5fe38b98228ec58c68b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
